chore: scriptsssssss

diff --git a/,usb-mount b/,usb-mount
--- a/,usb-mount
+++ b/,usb-mount
@@ -3,29 +3,29 @@
 # NOTE: use `lsblk` to identify the correct usbpart (if different then change usbpart value)
 # --> i know there are two error handling logic `set -e` and `|| {...; exit 1}`, im just paranoid kek
 
-set -e
+set -xeuo
 
 mountpoint="/mnt/$(whoami)/ejsmain"
 # mountpoint="/run/media/$(whoami)/ejsmain" # alternative mountpoint (can see in thunar)
-usbpart="/dev/sdb1"
+usbpart="/dev/sda1"
 
 # ensure that the mountpoint exists
 if [ ! -d "$mountpoint" ]; then
-	# create mountpoint
-	echo "[ INFO ] No ejsmain detected.... creating mountpoint at $mountpoint"
-	sudo mkdir -p "$mountpoint"
+  # create mountpoint
+  echo "[ INFO ] No ejsmain detected.... creating mountpoint at $mountpoint"
+  sudo mkdir -p "$mountpoint"
 fi
 
 # open with cryptsetup
 sudo cryptsetup open "$usbpart" ejsmain || {
-	echo "[ ERROR ] Unable to open device."
-	exit 1
+  echo "[ ERROR ] Unable to open device."
+  exit 1
 }
 
 # mount
 sudo mount /dev/mapper/ejsmain "$mountpoint" || {
-	echo "[ ERROR ] Unable to mount device."
-	exit 1
+  echo "[ ERROR ] Unable to mount device."
+  exit 1
 }
 
 echo "[ SUCCESS ] Device mounted at $mountpoint"
